[profile.default]
src = "src"
test = "test"
script = "script"
libs = ["lib"]
solc_version = "0.8.30"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
gas_reports = ["RealEstateToken"]

# Print logs
ffi = false
